name: Deploy Flask S3 Service

on:
  push:
    paths:
      - "flask-s3-service/**"
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ap-southeast-1

      - name: Build Docker image
        run: |
          docker build -t flask-s3-service ./flask-s3-service
          docker tag flask-s3-service:latest ${{ secrets.ECR_URI }}/flask-s3-service:latest

      - name: Push to ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}
          docker push ${{ secrets.ECR_URI }}/flask-s3-service:latest

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster flask-cluster \
            --service flask-s3-service \
            --force-new-deployment
